### ISSUE TITLE
`.zattrs` is not populated for one-level files

### ISSUE THREAD

**Issue by vaxenburg** [janelia-cellmap/n5_to_ome_zarr#3]
Maybe I'm missing something but it looks like the population of `.zattrs` will not work for "shallow" source files that have this sort of one-level structure:
```
.
├── attributes.json
├── s0
├── s1
└── s2
```
I think the code will not consider the root `zarr.hierarchy.Group` and will never get past [this line](https://github.com/janelia-cellmap/n5_to_ome_zarr/blob/main/src/n5_to_zarr.py#L64) in that shallow case. So looks like the code assumes at least a two-level hierarchy?

**Comment by yuriyzubov** [comment]
Should be [fixed](https://github.com/janelia-cellmap/n5_to_ome_zarr/commit/7e129ce4957f15c3fe39a8454148d7740a6f4f03) now.
